name: build

on:
  pull_request: 
  push:
    branches: [master]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: "${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}"
      - name: 'Build & Publish project'
        run: |
          ./build.sh Publish 
      - name: 'Publish ExpenseManager'
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseManager
          path: output/ExpenseManager
      - name: 'Publish ExpenseManager.Api'
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseManager.Api
          path: output/ExpenseManager.Api
      - name: 'Publish IdentityServer'
        uses: actions/upload-artifact@v4
        with:
          name: IdentityServer
          path: output/IdentityServer
          
  deploy-identity-server:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: 'https://bus1hero-IdentityServer.azurewebsites.net'
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: "${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}"
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: IdentityServer
          path: artifacts
      - name: Deploy to Azure Web App
        run: |
          ./build.sh deploy-to-azure --artifacts-path artifacts
        env:
          NUKE_AZURE_DEPLOY_SECRET: ${{ secrets.AZURE_DEPLOY_SECRET }}
          NUKE_AZURE_APPLICATION_ID: ${{ secrets.AZURE_APPLICATION_ID }}
          NUKE_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          NUKE_APP_NAME: bus1hero-IdentityServer
          NUKE_RESOURCE_GROUP: bus1heroDevEnvSetup
          
  deploy-webapp:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: 'https://ExpenseManager2.azurewebsites.net'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: "${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}"

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ExpenseManager
          path: artifacts

      - name: Deploy to Azure Web App
        run: |
          ./build.sh deploy-to-azure --artifacts-path artifacts
        env:
          NUKE_AZURE_DEPLOY_SECRET: ${{ secrets.AZURE_DEPLOY_SECRET }}
          NUKE_AZURE_APPLICATION_ID: ${{ secrets.AZURE_APPLICATION_ID }}
          NUKE_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          NUKE_APP_NAME: ExpenseManager2
          NUKE_RESOURCE_GROUP: bus1heroDevEnvSetup

  deploy-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: 'https://bus1hero.azurewebsites.net'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: "${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}"
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ExpenseManager.Api
          path: artifacts
          
      - name: Deploy to Azure Web App
        run: |
          ./build.sh deploy-to-azure --artifacts-path artifacts
        env:
          NUKE_AZURE_DEPLOY_SECRET: ${{ secrets.AZURE_DEPLOY_SECRET }}
          NUKE_AZURE_APPLICATION_ID: ${{ secrets.AZURE_APPLICATION_ID }}
          NUKE_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          NUKE_APP_NAME: bus1hero
          NUKE_RESOURCE_GROUP: bus1heroDevEnvSetup

  run-acceptance-tests-web:
    name: Run web acceptance tests
    runs-on: ubuntu-latest
    needs: [deploy-webapp, deploy-identity-server]
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: "${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}"
      - name: 'Run acceptance tests'
        env: 
          HOME: /root
          WebDriver__Headless: true
          WebDriver__Uri: 'https://expensemanager2.azurewebsites.net/'
        run: |
          ./build.sh RunAcceptanceTests --driver Web
          
          
  run-acceptance-tests-api:
    name: Run api acceptance tests
    runs-on: ubuntu-latest
    needs: [deploy-api, deploy-identity-server]
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: "${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}"
      - name: 'Run acceptance tests'
        run: |
          ./build.sh RunAcceptanceTests --driver Api
