name: build

on:
  pull_request: 
  push:
    branches: [master]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Build & Publish project'
        run: |
          ./build.sh Publish 
      - name: 'Publish Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseManager
          path: output/publish/ExpenseManager
      - name: 'Publish Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseManager.Api
          path: output/publish/ExpenseManager.Api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: 'https://bus1hero.azurewebsites.net'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ExpenseManager.Api
          path: artifacts
          
      - name: Deploy to Azure Web App
        run: |
          ./build.sh deploy-to-azure --artifacts-path artifacts
        env:
          NUKE_AZURE_DEPLOY_SECRET: ${{ secrets.AZURE_DEPLOY_SECRET }}
          NUKE_AZURE_APPLICATION_ID: ${{ secrets.AZURE_APPLICATION_ID }}
          NUKE_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          NUKE_APP_NAME: bus1hero
          NUKE_RESOURCE_GROUP: bus1heroDevEnvSetup

  run-acceptance-tests:
    name: Run Acceptance tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run acceptance tests'
        run: |
          ./build.sh RunAcceptanceTests
