name: build

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Nuke'
        run: |
          ./build.sh Publish 
      - name: 'Publish Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: output/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Staging'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: artifacts
          
      - run: ls -la
          
      - name: Deploy to Azure Web App
        run: |
          ./build.sh Publish

  run-acceptance-tests:
    name: Run Acceptance tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run acceptance tests'
        run: |
          ./build.sh RunAcceptanceTests
