name: build

on:
  pull_request: 
  push:
    branches: [master]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Build & Publish project'
        run: |
          ./build.sh Publish 
      - name: 'Publish ExpenseManager'
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseManager
          path: output/ExpenseManager
      - name: 'Publish ExpenseManager.Api'
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseManager.Api
          path: output/ExpenseManager.Api